apiVersion: v1
kind: Service
metadata:
  name: nginx-4
  namespace: default
  labels:
    zone: serverfarm
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: nginx-4
  type: LoadBalancer
