apiVersion: v1
kind: Service
metadata:
  name: nginx-5
  namespace: default
  labels:
    zone: dmz
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: nginx-5
  type: LoadBalancer
