apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-4
  namespace: default
spec:
  selector:
    matchLabels:
      app: nginx-4
  template:
    metadata:
      labels:
        app: nginx-4
    spec:
      containers:
      - name: nginx-4
        image: nginx:1
        imagePullPolicy: IfNotPresent
        ports:
        - name: http
          containerPort: 80
        volumeMounts:
        - name: nginx-config
          mountPath: /usr/share/nginx/html
      volumes:
      - name: nginx-config
        configMap:
          name: nginx-4
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-4
  namespace: default
data:
  index.html: |
    <!DOCTYPE html>
    <html lang="en">
    <head>
        <title>GPrakosa</title>
    </head>
    <body>
        <p>This is running on <strong>Server Farm</strong> zone also!<p>
    </body>
    </html>
